import type { NextPage } from "next"
import Head from 'next/head'
import Header from "../components/Header"
import Hero from "../components/Hero"
import About from "../components/About"
import Experience from "../components/Experience"
import Skill from "../components/Skill"
import Projects from "../components/Projects"
import ContactScreen from "../components/ContactScreen"
import Link from 'next/link'
import styles from '../styles/Home.module.css'
import Image from "next/image"
import myFace from "../public/profile.png"

export default function Home() {
  return (
    <div className="bg-[rgb(36,36,36)] text-white h-screen snap-y snap-mandatory overflow-y-scroll overflow-x-hidden z-0 scrollbar scrollbar-track-gray-400/20 scrollbar-thumb-[#F7AB0A]/80
    scrollbar-thin
    ">
      <Head>
        <title>Ken&apos;s Portfolio</title>
        {/* <meta name="description" content="Generated by create next app" /> */}
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>

      {/* Header */}
      <Header />

      {/* Hero */}
      <section id="hero" className="snap-start">
        <Hero />
      </section>
      

      {/* About */}
      <section id="about" className="snap-center">
        <About />
      </section>

      {/* Experience */}
      <section id="experience" className="snap-center">
        <Experience />
      </section>

      {/* Skills */}
      <section id="skills" className="snap-center">
        <Skill />
      </section>

      {/* Projects */}
      <section id="projects" className="snap-start">
        <Projects />
      </section>

      {/* Contact Me */}
      <section id="contactMe" className="snap-center">
        <ContactScreen />
      </section>

      <Link href="#hero">
        <footer className="sticky bottom-5 w-full cursor-pointer">
          <div className="flex items-center justify-center">
            <Image
            className="h-10 w-10 rounded-full filter grayscale hover:grayscale-0 cursor-pointer"
            src={myFace}
            alt=""
            />
          </div>
        </footer>
      </Link>
    </div>
  )
}
